---
deployment:
  tasks:
    - current_path=`pwd`
    - if [ $current_path == "/home/seky5115/repositories/sk-web-landing" ]; then export DEPLOYPATH=/home/seky5115/; fi;
    - /bin/cp -R * $DEPLOYPATH/sk-web-landing/
    - /bin/cp -r public/admin-template $DEPLOYPATH/public_html/
    - /bin/cp -r public/calendar-template $DEPLOYPATH/public_html/
    - /bin/cp -r public/images $DEPLOYPATH/public_html/
    - /bin/cp -r public/landing-template $DEPLOYPATH/home/public_html/
    - /bin/cp -r public/login-template $DEPLOYPATH/home/public_html/
